micronaut:
  server:
    port: -1
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  session:
    http:
      redis:
        enabled: true
        namespace: 'micronaut_example:sessions'
        write-mode: BACKGROUND
        enable-keyspace-events: false
        valueSerializer: io.micronaut.jackson.serialize.JacksonObjectSerializer

endpoints:
  info:
    enabled: true
    sensitive: false

consul:
  client:
    registration:
      enabled: true

tracing:
  zipkin:
    enabled: true
    http:
      url: http://127.0.0.1:9411
    sampler:
      probability: 1

redis:
  uri: redis://127.0.0.1
  ssl: true
  timeout: 30s
